name: CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello from the server
        run: |
          echo Hello from the server!

      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Setting up Node.js Environment
        uses: actions/setup-node@v4.3.0
      
      - name: Getting dependencies
        run: |
          npm install

      - name: Turnstyle in action
        uses: softprops/turnstyle@v2 
        with: 
          job-to-wait-for: "build"
          step-to-wait-for: "Updating the Image Tag"
          poll-interval-seconds: 10
          same-branch-only: true

      - name: Tests
        run: |
          npm run test
      
      - name: Updating the Image tag
        run: |
          sleep 20
          echo "Updated the image tag"