# name: CI
# on: 
#   push:
#     branches:
#       - main
#   pull_request:
#     branches: 
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Hello from the server
#         run: |
#           echo Hello from the server!

#       - name: Checkout the code
#         uses: actions/checkout@v4.2.2

#       - name: Setting up Node.js Environment
#         uses: actions/setup-node@v4.3.0

#       - name: Running tests
#         run: |
#           npm run test

#       - name: Completion ACK
#         run: | 
#           echo Workflow completed
